name: Deploy profile-hub UI

on:
  push:
    branches: [ "main", "development" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set tags
        id: tags
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TAG1=prod-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "TAG2=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG1=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "TAG2=dev-latest" >> $GITHUB_OUTPUT
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build -t sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG1 }} -t sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG2 }} .
      - name: push image to docker
        run: |
          docker push sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG1 }}
          docker push sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG2 }}
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 (pull latest + compose up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /opt/profile-hub
            docker compose pull
            docker compose up -d
            docker image prune -f