name: Deploy profile-hub UI

on:
  push:
    branches: [ "main", "development" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set tags
        id: tags
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_OUTPUT
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TAG1=prod-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "TAG2=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG1=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
            echo "TAG2=dev-latest" >> $GITHUB_OUTPUT
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        run: docker build --build-arg VITE_APP_VERSION=${{ steps.tags.outputs.SHORT_SHA }} -t sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG1 }} -t sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG2 }} .
      - name: push image to docker
        run: |
          docker push sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG1 }}
          docker push sthireveedhi/profile-hub-ui:${{ steps.tags.outputs.TAG2 }}
